# Akko's tmux configuration file
# 0.2

# Icons

set -g @my_icon_calendar "\ueab0"
set -g @my_icon_clock "\uf017"
set -g @my_icon_ethernet "\U000f0c53"
set -g @my_icon_keyboard "\uf11c"
set -g @my_icon_linux "\uebc6"
set -g @my_icon_macos "\ue711"
set -g @my_icon_wifi "\uf1eb"
set -g @my_icon_timer "\U000f0109"

set -g prefix C-a
unbind C-b

# Reload config file
bind r source-file ~/.tmux.conf \; display "What does it mean to be human?"

# I'm not a machine (yet)
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g renumber-windows on

# Reduce time
set -sg escape-time 0

bind C-a send-prefix

# Create new panes
bind < split-window -h -c "#{pane_current_path}"
bind > split-window -v -c "#{pane_current_path}"

# Moving through panes vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Colors
set -g default-terminal "screen-256color"

# Don't rename the window
set -g allow-rename off

# Mousewheel
#set-option -g mouse on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on
#set -g mouse-select-window on
#bind -n WheelUpPane copy-mode

# Status bar
set -g status-position bottom
set -g status-justify centre
set -g status-bg default
set -g status-fg default
set -g window-status-format " #I #W#F "
set -g window-status-current-format " #I #W#F "
set -g window-status-current-style reverse

# Left status bar: session name
set -g status-left-length 50
set -g status-left "#[reverse] #(if [[ $(uname) == 'Darwin' ]]; then echo #{@my_icon_macos}; else echo #{@my_icon_linux}; fi) #(whoami) #[noreverse] #{@my_icon_timer} #(uptime | awk -F'[ ,]+' '{print $3}') #[reverse] #{@my_icon_keyboard} #(bash ~/.config/sh/keyboard.sh) "

# Right status bar: host name, date and time
set -g status-right-length 50
set -g status-right "#[reverse] #(bash ~/.config/sh/net.sh) #{@my_icon_ethernet} #[noreverse] %d/%m/%y #{@my_icon_calendar} #[reverse] %H:%M #{@my_icon_clock} "

# Monochrome message bar
set -g message-style bg=default,fg=default
set -g message-command-style bg=default,fg=default

# Pane separator
set -g pane-border-format "[#{pane_index}]"
set -g pane-border-indicators arrows
set -g pane-border-lines simple
set -g pane-border-status bottom
set -g pane-border-style fg=black

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
