vim.pack.add({
  { src = 'https://github.com/catppuccin/nvim', name = 'catppuccin'},
  { src = 'https://github.com/ellisonleao/gruvbox.nvim'},
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter'},
  { src = 'https://github.com/mbbill/undotree'},
  { src = 'https://github.com/tpope/vim-fugitive'},
  { src = 'https://github.com/airblade/vim-gitgutter'},
  { src = 'https://github.com/nvim-lua/plenary.nvim'},
  { src = 'https://github.com/nvim-telescope/telescope.nvim', branch = '0.1.x'},
  { src = 'https://github.com/BurntSushi/ripgrep'},
  { src = 'https://github.com/nvim-lua/popup.nvim'},
  { src = 'https://github.com/nvim-telescope/telescope-media-files.nvim'},
  { src = 'https://github.com/nvim-tree/nvim-tree.lua'},
  { src = 'https://github.com/nvim-tree/nvim-web-devicons'},
  { src = 'https://github.com/nvim-lualine/lualine.nvim'},
  { src = 'https://github.com/akinsho/bufferline.nvim', tag = '*'}, 
  { src = 'https://github.com/neovim/nvim-lspconfig'},
  { src = 'https://github.com/mason-org/mason.nvim'},
  { src = 'https://github.com/mason-org/mason-lspconfig.nvim'},
  { src = 'https://github.com/L3MON4D3/LuaSnip'},
  { src = 'https://github.com/mfussenegger/nvim-lint'},
  { src = 'https://github.com/hrsh7th/cmp-buffer'},
  { src = 'https://github.com/hrsh7th/cmp-cmdline'},
  { src = 'https://github.com/hrsh7th/cmp-nvim-lsp'},
  { src = 'https://github.com/hrsh7th/cmp-path'},
  { src = 'https://github.com/hrsh7th/nvim-cmp'},
  { src = 'https://github.com/neovim/nvim-lspconfig'},
  { src = 'https://github.com/fatih/vim-go'},
  { src = 'https://github.com/rust-lang/rust.vim'},
  { src = 'https://github.com/elixir-editors/vim-elixir'},
  { src = 'https://github.com/numToStr/Comment.nvim'},
})
