alias c="cd /Volumes/Nano/Code"
alias cat="bat"
alias gop="cd $GOPATH/src"
alias hn="w3m https://news.ycombinator.com/"
alias htop="btm"
alias images='wget -nd -H -p -A jpg,jpeg,png,gif -e robots=off'
alias kubectl="minikube kubectl --"
alias lc="tokei"
alias ll="eza -l --icons --group-directories-first"
alias ls="eza --icons --group-directories-first"
alias mpd="nohup mpv http://192.168.0.3:8050/ > /dev/null 2>&1 &"
alias n="cd /Volumes/Nano"
alias tt="tmux new -s wako"
alias unrar='unrar x'
alias update="brew update && brew upgrade && mise plugin ls | xargs mise plugin upgrade"
alias vim="nvim"
