#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#################################################
#Terminal urxvt
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xrdb -merge ~/.Xresources &
setxkbmap -model pc104 -layout latam -option grp:alt_shift_toggle &
#Terminal urxvt
##################################################
nitrogen --restore &
xbindkeys &
xset -b &
mpd &
exec i3
